### ISSUE TITLE
[Bug] Perms Not Working

### ISSUE THREAD

**Issue by BroCrows** [ElectroGamesYT/MaintenanceMode#1]
Hello! So when I turned maintenance mode on, none of my builders or testers that have the perm could join. I decided to deop myself and even I couldnt join.
So for some reason the perm isnt working

**Comment by ElectroGamesDev** [comment]
Do they have the permission `maintenancemode.bypass`?

**Comment by BroCrows** [comment]
Yes

**Comment by BroCrows** [comment]
This bug can probably be closed because RankSystem is bad.
But I think I was having the same problem with PurePerms

**Comment by ElectroGamesDev** [comment]
Hmmm.... Just checked the code and it should be working... Ill look into it when I have time.
